### ISSUE TITLE
addToWaitList throws 403 error when target user has no playlists

### ISSUE THREAD

**Issue by AtenRIP** [plugCubed/plugAPI#154]
If the bot tries to add a user to the waitlist, and the user has no playlists and/or songs, the bot crashes with this error in log:
`Error: https://plug.dj/_/booth/add responded with 403 (FORBIDDEN
    at process.nextTick (D:\PhpstormProjects\HoRM\rockbot-v2\node_modules\plugapi\lib\client.js:625:39)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`
The error doesn't seem to be catchable. At least not like this:
`
try {
  data.from.addToWaitList();
}
catch (error) {
  bot.sendChat('Error adding a user to waitlist.');
  console.error(error);
}
`

**Comment by goto-bus-stop** [comment]
You can use `bot.moderateAddDJ` with a Node-style callback instead:

```js
bot.moderateAddDJ(data.from.id, function (err) {
  if (err) bot.sendChat('Error adding a user to waitlist.')
})
```

**Comment by AtenRIP** [comment]
At first, I thought the issue is solved by your response, but apparently not. Even moderateAddDJ does the same thing.
```
bot.moderateAddDJ(data.from.id, (err) => {
  bot.sendChat('Error adding a user to waitlist.');
  console.error(err);
});
```
Again, bot crashes with:
```
/home/tom/PhpstormProjects/plug/rockbot-v2/node_modules/plugapi/lib/client.js:625
                                throw new Error(`${opts.url} responded with ${err.statusCode} (${err.statusMessage}`);
                                ^

Error: https://plug.dj/_/booth/add responded with 403 (FORBIDDEN
    at process.nextTick (/home/tom/PhpstormProjects/plug/rockbot-v2/node_modules/plugapi/lib/client.js:625:39)
    at process._tickCallback (internal/process/next_tick.js:176:11)

Process finished with exit code 1
```

**Comment by mortenn** [comment]
The same thing happens if the boin tries to join itself with an empty playlist:
```
/home/kawaiibot/bot.js/node_modules/plugapi/lib/client.js:625
                                throw new Error(`${opts.url} responded with ${err.statusCode} (${err.statusMessage}`);
                                ^

Error: https://plug.dj/_/booth responded with 403 (FORBIDDEN
    at process.nextTick (/home/kawaiibot/bot.js/node_modules/plugapi/lib/client.js:625:39)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
