### ISSUE TITLE
Errors trying to perform npm install plugapi

### ISSUE THREAD

**Issue by HarryMcKenzie** [plugCubed/plugAPI#156]
I'm a noob trying to potentially create a bot that's better than my current one (forked from basicBot) with this, not sure where to start here but I'm getting these errors trying to install the environment on my headless machine. 

```
npm install plugapi
(node:31213) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/root/node_modules/plugapi/node_modules/chalk'
npm ERR! error rolling back  plugapi@5.1.0 { Error: ENOTEMPTY: directory not empty, rmdir '/root/node_modules/plugapi/node_modules/chalk'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/root/node_modules/plugapi/node_modules/chalk' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.62-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "plugapi"
npm ERR! cwd /root
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /root/.npm/retry/0.12.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/deasync/0.1.13/package.tgz
-
> utf-8-validate@4.0.2 install /root/node_modules/plugapi/node_modules/utf-8-validate
> prebuild-install || node-gyp rebuild

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/node_modules/plugapi/node_modules/utf-8-validate/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node_modules/plugapi/node_modules/utf-8-validate/node_modules/prebuild-install/bin.js:7:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
gyp: binding.gyp not found (cwd: /root/node_modules/plugapi/node_modules/utf-8-validate) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.62-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node_modules/plugapi/node_modules/utf-8-validate
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian


> bufferutil@3.0.5 install /root/node_modules/plugapi/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/node_modules/plugapi/node_modules/bufferutil/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node_modules/plugapi/node_modules/bufferutil/node_modules/prebuild-install/bin.js:7:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
gyp: binding.gyp not found (cwd: /root/node_modules/plugapi/node_modules/bufferutil) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.62-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node_modules/plugapi/node_modules/bufferutil
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@4.0.2
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@3.0.5
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

```

**Comment by thedark1337** [comment]
looks like you installed the debian node package maybe (npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21)

I'd suggest using: https://github.com/nodesource/distributions for installing nodejs/npm

that npm version is VERY old (the current npm is v6 or something like that)

Let me know if you get any issues after upgrading node/npm via that method and installing plugAPI again

**Comment by HarryMcKenzie** [comment]
Thanks, that was indeed the problem!
