### ISSUE TITLE
Error after connection with other account

### ISSUE THREAD

**Issue by HarryMcKenzie** [plugCubed/plugAPI#157]
It works fine with my own account, but shortly after connecting with a newly made account for the bot it gives this error shortly after joining the room successfully.

```
/home/nodeworkspace/node_modules/plugapi/lib/client.js:625
                                throw new Error(`${opts.url} responded with ${err.statusCode} (${err.statusMessage}`);
                                ^

Error: https://plug.dj/_/booth responded with 403 (FORBIDDEN
    at process.nextTick (/home/nodeworkspace/node_modules/plugapi/lib/client.js:625:39)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

```

**Comment by mortenn** [comment]
This will only happen if the bot is written to join the booth on startup, which as far as I know/can tell is not default behaviour.
If your bot is calling joinBooth, it should ensure a playlist exists and is loaded with at least one song first.

Whether or not PlugAPI should prevent calling code from trying to join without a playlist will have to be decided upon by the team, I think.

I would however propose a change where the callback is called with an error rather than an exception being thrown.
