### ISSUE TITLE
Feb 18th 2015 chat server revert

### ISSUE THREAD

**Issue by foodbandlt** [plugCubed/plugAPI#63]
Just FYI, not an issue, but it looks like Plug version 1.2.6.6462 has just reverted back to the old chat server once more.  PlugAPI@3.1.0 ahoy!

**Comment by foodbandlt** [comment]
The recent update to 1.2.7.6480 uses the new chat server, so the current one works now.  The only thing now is that the socket exits with code 1000 and the bot occasionally spends the next three minutes reconnecting and disconnecting.  I've also gotten this once or twice when trying to reconnect:

Log:
```
18 Feb 19:39:39 [WARNING]  [plugAPI]  [Socket Server] Closed with code 1000
18 Feb 19:39:39 [INFO]     [plugAPI]  [Socket Server] Reconnecting
TypeError: Cannot read property 'split' of undefined
    at Request._callback (C:\Users\Foodbandlt\Dropbox\CTSBot\src\node_modules\pl
ugapi\bin\src\client.js:654:13)
    at Request.self.callback (C:\Users\Foodbandlt\Dropbox\CTSBot\src\node_module
s\plugapi\node_modules\request\request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Foodbandlt\Dropbox\CTSBot\src\node_modules\
plugapi\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Foodbandlt\Dropbox\CTSBot\src\node_
modules\plugapi\node_modules\request\request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
