### ISSUE TITLE
Why is 'session' not defined?

### ISSUE THREAD

**Issue by ayatojhans** [plugCubed/plugAPI#65]
Sometimes I get this error:
```
TypeError: Cannot read property 'session' of undefined
    at CookieHandler.exports.contain (C:\FOO\node_modules\plugapi\bin\src\cookie.js:35:12)
    at [object Object].PlugAPI.connect (C:\FOO\node_modules\plugapi\bin\src\client.js:1359:10)
    at WebSocket.messageHandler (C:\FOO\node_modules\plugapi\bin\src\client.js:899:13)
    at WebSocket.emit (events.js:129:20)
    at WebSocket.<anonymous> (C:\FOO\node_modules\plugapi\bin\src\client.js:691:17)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (C:\FOO\node_modules\plugapi\node_modules\ws\lib\WebSocket.js:798:10)
    at C:\FOO\node_modules\plugapi\node_modules\ws\lib\Receiver.js:473:18
    at Receiver.applyExtensions (C:\FOO\node_modules\plugapi\node_modules\ws\lib\Receiver.js:360:5)
    at C:\FOO\node_modules\plugapi\node_modules\ws\lib\Receiver.js:462:14
```

What does it mean? What is causing it? How can I avoid it?

**Comment by thedark1337** [comment]
It can be a lot of reasons why that happens.

1) Are you running that bot only once, I've had issues with my bot not shutting down properly and running it more than once causes the session is undefined?

2) Which plugAPI version are you running? It's recommended to run the latest version.

3) Try deleting the cookies.tmp file in the node_modules/plugapi folder, that's the cache file we uses to save session information.

**Comment by zudomc** [comment]
Are you using the same account on the bot and the site?

**Comment by ayatojhans** [comment]
I've seen this error _sometimes_ when I accidentaly log in with the same account I'm using for the bot on plugDj. Some other times, happens randomly.

I'm using the latest version.

I'll try deleting that file.

**Comment by thedark1337** [comment]
That's why, you can't sign on the same account twice. The error just means you've signed in more than once either running the bot twice or accidentally signing in on the browser
